@startuml

Interface NamedEntity{
    String getText()
    String getType()
}

Interface NamedEntityRecognizer{
    NamedEntity[] recognize(String text)
}

Class NamedEntityRecognizerManager{

    NamedEntityRecognizer getRecognizer(String id)
    Map<NamedEntityRecognizer> namedEntityRecognizerMap = new HashMap<>();
}

class NamedEntityImpl{
    String getText()
    String getType()
}
Class PersonEntity{
    String getText()
    String getType()
}
Class PersonNamedEntityRecognizer{
    NamedEntity[] recognize(String text);
}
Enum PersonNamedEntityRecognizerFactory{
    REPORTER
    EMAIL
}
NamedEntityRecognizer ...> NamedEntity: return
NamedEntityRecognizer <|.. PersonNamedEntityRecognizer
NamedEntityRecognizerManager o--- PersonNamedEntityRecognizer
NamedEntity <|... NamedEntityImpl
NamedEntityImpl <|-- PersonEntity

PersonNamedEntityRecognizerFactory ..> NamedEntityRecognizer:create
PersonNamedEntityRecognizerFactory <.. NamedEntityRecognizerManager
'PersonNamedEntityRecognizer ...> PersonEntity : return
'PersonNamedEntityRecognizerFactory ---> PersonNamedEntityRecognizer : return
'
'NamedEntity <|... PersonEntity

'NamedEntityRecognizer <... NamedEntityRecognizerManager: return
'NamedEntityRecognizer <|... PersonNamedEntityRecognizer


@enduml